// ingredientSubstitutions.js
export const ingredientSubstitutions = {
  "spaghetti": "zucchini noodles or gluten-free pasta",
  "shrimp": "chicken breast or tofu",
  "butter": "coconut oil or olive oil",
  "garlic": "garlic powder or roasted garlic",
  "red pepper flakes": "cayenne pepper or paprika",
  "chicken broth": "vegetable broth or water with bouillon",
  "lemon juice": "lime juice or vinegar",
  "parsley": "cilantro or basil",
  "parmesan cheese": "nutritional yeast or vegan parmesan",
  "milk": "almond milk, soy milk, oat milk, or coconut milk",
  "yogurt": "coconut yogurt, almond yogurt, or dairy-free sour cream",
  "egg": "flaxseed meal + water, chia seed gel, or aquafaba (for baking)",
  "all-purpose flour": "whole wheat flour, almond flour, or oat flour",
  "white sugar": "honey, maple syrup, agave nectar, or coconut sugar",
  "brown sugar": "coconut sugar or date paste",
  "heavy cream": "coconut cream or cashew cream",
  "sour cream": "vegan sour cream or plain Greek yogurt",
  "cream cheese": "vegan cream cheese or blended tofu",
  "bread crumbs": "crushed crackers, rolled oats, or almond flour",
  "honey": "maple syrup, agave nectar, or brown rice syrup",
  "mayonnaise": "vegan mayo or mashed avocado",
  "bacon": "tempeh bacon, coconut bacon, or smoked paprika seasoning",
  "ground beef": "ground turkey, ground chicken, lentils, or plant-based meat substitutes",
  "rice": "cauliflower rice, quinoa, or bulgur",
  "pasta": "chickpea pasta, lentil pasta, or spiralized vegetables",
  "cheese": "nutritional yeast, cashew cheese, or vegan cheese",
  "whipped cream": "coconut whipped cream or aquafaba whipped cream",
  "gelatin": "agar-agar or pectin",
  "buttermilk": "dairy-free milk + lemon juice or vinegar",
  "soy sauce": "coconut aminos or tamari",
  "vinegar": "lemon juice or apple cider vinegar",
  "vanilla extract": "vanilla powder or almond extract",
  "cornstarch": "arrowroot powder or tapioca starch",
  "chocolate chips": "cacao nibs, carob chips, or dairy-free chocolate chips",
};